keys:
  - &admin age19g0znk30e6m72w6vd6swjvj4ae8vzd5m97u0rxwcnh9x4u5eaupsdtedfx
creation_rules:
  - path_regex: hosts/headscale/secrets.yaml
    key_groups:
      - age:
        - *admin
        - age13frqp6gdcjk7u0ypgm8szcpj3gqtj5kjuzmflxxxzgdw9lndx4kqn7a7ag
  - path_regex: hosts/werkstatt-prodesk/secrets.yaml
    key_groups:
      - age:
        - *admin
        - age1klzgkrj7ra3h5lwdpay3kdpcgz0dl6jm7wc2fswy5grhra6r944s2atk04
