keys:
  - &admin age19g0znk30e6m72w6vd6swjvj4ae8vzd5m97u0rxwcnh9x4u5eaupsdtedfx
creation_rules:
  - path_regex: hosts/headscale/secrets.yaml
    key_groups:
      - age:
        - *admin
        - age1mqswtt2mtlzspkdn86w6w0nv3sj3f3u8cpgpzv84dt5jt65nh57sq8nr9s
